[build]
  command = "npm run build"
  publish = "build/"
  environment = { REACT_APP_BASEURL = "https://api-bootcamp.do.dibimbing.id", REACT_APP_APIKEY = "w05KkI9AWhKxzvPFtXotUva-", REACT_APP_JWTTOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im9va2V5MTI0QGdtYWlsLmNvbSIsInVzZXJJZCI6ImViYmQ5MjNlLTZjYWQtNGQwZC1iNDQxLTFlZDNiNjM3NmJjYyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4Mzg5Mzk2Mn0.xhSHCClk6uuoTkXYJrokpz2lBhWGRNCEWw1YUFAgJEY" }
